services:
  contacts-postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - contacts_data:/var/lib/postgresql/data
  #  pgadmin:
  #    container_name: pgadmin_container
  #    image: dpage/pgadmin4
  #    depends_on:
  #      - smp-postgres
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
  #      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #      PGADMIN_CONFIG_SERVER_MODE: 'False'
  #    volumes:
  #      - ./pgadmin:/var/lib/pgadmin
  #    ports:
  #      - ${PGADMIN_PORT:-5050}:80
  #    restart: unless-stopped
  contacts-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ConnectionStrings__DefaultConnection=${CONTRACTS_CONNECTION}
    build:
      dockerfile: ./src/Contacts.Api/Dockerfile
    image: contacts-api
    container_name: contacts-api-local
    ports:
      - "5171:80"
    depends_on:
      - contacts-postgres
#  web-client:
#    image: nginx:alpine
#    volumes:
#      - ./src/web-app-vanilla:/usr/share/nginx/html
#    ports:
#      - "3500:80"

volumes:
  contacts_data: